# Generated by Django 5.1.5 on 2025-01-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Worker',
        ),
    ]
